
name: pytestCI

on:
  push:
    branches:
      - 'master'
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: pip install
      run: pip install -U -r requirements.txt
    - name: execute pytest
      run: pytest
    
