
name: entry_test_pypi

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: pip install
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
      - name: execute pytest
        run: pytest
  register:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: pip install
        run: |
          python -m pip install --upgrade pip
          pip install -U wheel twine
      - name: build wheel
        run: python setup.py sdist bdist_wheel
      - name: Init .pypirc
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          echo -e "[distutils]" >> ~/.pypirc
          echo -e "index-servers=" >> ~/.pypirc
          echo -e "    pypi" >> ~/.pypirc
          echo -e "    testpypi" >> ~/.pypirc
          echo -e "[pypi]" >> ~/.pypirc
          echo -e "username: ${PYPI_USERNAME}" >> ~/.pypirc
          echo -e "password: ${PYPI_PASSWORD}" >> ~/.pypirc
          echo -e "[testpypi]" >> ~/.pypirc
          echo -e "repository: https://test.pypi.org/legacy/" >> ~/.pypirc
          echo -e "username: ${TESTPYPI_USERNAME}" >> ~/.pypirc
          echo -e "password: ${TESTPYPI_PASSWORD}" >> ~/.pypirc
      - name: register test_pypi
        run: twine upload -r testpypi dist/*
