name: build test for Pull requests

on:
  push:
    pull_request:
      - '*'

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: pip install
        run: pip install -U -r requirements.txt
      - name: execute pytest
        run: pytest

  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: pip install
        run: pip install -U wheel twine
      - name: build wheel
        run: python setup.py sdist bdist_wheel
